# Docker Compose with Caddy for automatic HTTPS
version: "3.8"

services:
  # Your Node.js API
  api:
    build: .
    container_name: cycleoptima-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - app-network
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: cycleoptima-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secretpassword}
      - MYSQL_DATABASE=${DB_NAME:-cycleoptima}
      - MYSQL_USER=${DB_USER:-apiuser}
      - MYSQL_PASSWORD=${DB_PASSWORD:-apipassword}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Caddy for automatic HTTPS
  caddy:
    image: caddy:2-alpine
    container_name: cycleoptima-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
